# Generated by Django 5.1.1 on 2024-12-09 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskModel', '0002_taskmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='category',
        ),
    ]
