# Generated by Django 5.1.1 on 2024-12-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskCatagoryModel', '0005_remove_taskcatergory_task'),
        ('TaskModel', '0003_remove_taskmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='taskcategory', to='TaskCatagoryModel.taskcatergory'),
        ),
    ]
