# Generated by Django 5.1.1 on 2024-12-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskCatagoryModel', '0005_remove_taskcatergory_task'),
        ('TaskModel', '0004_taskmodel_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='categories',
            field=models.ManyToManyField(to='TaskCatagoryModel.taskcatergory'),
        ),
    ]
