# Generated by Django 5.1.1 on 2024-12-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskCatagoryModel', '0001_initial'),
        ('TaskModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcatergory',
            name='task',
            field=models.ManyToManyField(related_name='categories', to='TaskModel.taskmodel'),
        ),
    ]
