# Generated by Django 5.1.1 on 2024-12-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskCatagoryModel', '0003_alter_taskcatergory_task'),
        ('TaskModel', '0003_remove_taskmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcatergory',
            name='task',
            field=models.ManyToManyField(to='TaskModel.taskmodel'),
        ),
    ]
